/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Tesseract: {
      address: "0x82dc47734901ee7d4f4232f398752cb9dd5daccc",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "initialOwner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createSeller",
          inputs: [
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "imageURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "contact",
              type: "string",
              internalType: "string",
            },
          ],
          outputs: [
            {
              name: "sellerId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "createService",
          inputs: [
            {
              name: "sellerId",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "outputURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "inputSpecsURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "outputSpecsURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "price",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "serviceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deleteSeller",
          inputs: [
            {
              name: "sellerId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "deleteService",
          inputs: [
            {
              name: "serviceId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "getSellersByOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256[]",
              internalType: "uint256[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "idToSeller",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "id",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "name",
              type: "string",
              internalType: "string",
            },
            {
              name: "bio",
              type: "string",
              internalType: "string",
            },
            {
              name: "imageURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "contact",
              type: "string",
              internalType: "string",
            },
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "idToService",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "outputURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "inputSpecsURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "outputSpecsURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "price",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "completedServices",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "failedServices",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totReviews",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reputation",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "sellerId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "owner",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "ownerSellerCounter",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "renounceOwnership",
          inputs: [],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "sellerCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "sellerToServices",
          inputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "outputURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "inputSpecsURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "outputSpecsURI",
              type: "string",
              internalType: "string",
            },
            {
              name: "price",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "completedServices",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "failedServices",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "totReviews",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "reputation",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "sellerId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "serviceCounter",
          inputs: [],
          outputs: [
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "transferOwnership",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "transferSeller",
          inputs: [
            {
              name: "newOwner",
              type: "address",
              internalType: "address",
            },
            {
              name: "sellerId",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "event",
          name: "OwnershipTransferred",
          inputs: [
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SellerCreated",
          inputs: [
            {
              name: "sellerId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SellerDeleted",
          inputs: [
            {
              name: "sellerId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SellerTransferred",
          inputs: [
            {
              name: "sellerId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "previousOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "newOwner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ServiceCreated",
          inputs: [
            {
              name: "serviceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "sellerId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "ServiceDeleted",
          inputs: [
            {
              name: "serviceId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "sellerId",
              type: "uint256",
              indexed: true,
              internalType: "uint256",
            },
            {
              name: "owner",
              type: "address",
              indexed: true,
              internalType: "address",
            },
          ],
          anonymous: false,
        },
        {
          type: "error",
          name: "OwnableInvalidOwner",
          inputs: [
            {
              name: "owner",
              type: "address",
              internalType: "address",
            },
          ],
        },
        {
          type: "error",
          name: "OwnableUnauthorizedAccount",
          inputs: [
            {
              name: "account",
              type: "address",
              internalType: "address",
            },
          ],
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1752623397.json",
      deploymentScript: "Deploy.s.sol",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
